# yaml-language-server: $schema=../schemas/paper-plugin.schema.json
name: LPC MiniMessage X
version: '${version}'
main: com.vomlabs.lpcmmx.Main
api-version: '1.21'
authors: [ItzzMateo, VOMLabs]
depend: [LuckPerms]
softdepend: [PlaceholderAPI, Vault]
description: Edit version of wikmors Legacy LPC plugin (MiniMessage Support 1.21.11)
website: https://modrinth.com/plugin/lpc-chat
commands:
  lpc:
    description: Reload the configuration.
    permission: lpc.reload
    usage: "Usage: /lpc reload"
